### ISSUE TITLE
Question: why the code use ```model_output``` instead of ```model_output.log_softmax()```?

### ISSUE THREAD

**Issue by enkeejunior1** [kuleshov-group/mdlm#10]
It may be a dumb question, but I thought \( x_{\theta}(z_t) \) represents a probability. Shouldn't we add `model_output.log_softmax()`? I think the current form only increases the logit value, not the probability.

https://github.com/kuleshov-group/mdlm/blob/20c706c9d62a31b998202fc3a6e748421751129c/diffusion.py#L884C14-L884C15

```python
    log_p_theta = torch.gather(
      input=model_output, # -> model_output.log_softmax(dim=-1) ?
      dim=-1,
      index=x0[:, :, None]).squeeze(-1)
```

**Comment by s-sahoo** [comment]
Valid question. If you notice, the output of the denoising model goes through these functions [[function1](https://github.com/kuleshov-group/mdlm/blob/20c706c9d62a31b998202fc3a6e748421751129c/diffusion.py#L312), [function2](https://github.com/kuleshov-group/mdlm/blob/20c706c9d62a31b998202fc3a6e748421751129c/diffusion.py#L261)] to compute `model_output` which is equivalent to what you mentioned.
