### ISSUE TITLE
Memory Increase during Training

### ISSUE THREAD

**Issue by YuxuanSong** [kuleshov-group/mdlm#8]
Hi!

Congratulations on the nice work! 

I am running the experiments with A100s, and I encountered a memory-increasing issue and finally OOM during training.  I want to know whether you have also encountered similar phenomena. Could you share the memory settings for your A100 servers?

Best,
Yuxuan

**Comment by Skylion007** [comment]
We trained on 40GB and 80GB A100 servers without ever encountering this issue.. I would check your PyTorch version and make sure it's up to date.
